/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * JavaScript-exposed Actra class.
 *
 * Compilation occurs during construction.
 * Evaluation is stateless and deterministic.
 */
export declare class Actra {
  /**
   * Creates a new Actra instance.
   *
   * Parameters:
   * - `schema_yaml`: YAML schema definition
   * - `policy_yaml`: YAML policy definition
   * - `governance_yaml`: Optional governance constraints
   *
   * Throws:
   * - `Error` if parsing or compilation fails.
   */
  constructor(schemaYaml: string, policyYaml: string, governanceYaml?: string | undefined | null)
  /**
   * Evaluates the compiled policy against runtime input.
   *
   * Expected input format:
   * {
   *   action: { ... },
   *   actor: { ... },
   *   snapshot: { ... }
   * }
   *
   * Missing keys should be provided as empty objects.
   *
   * Returns:
   * {
   *   effect: "allow" | "block" | "require_approval",
   *   matched_rule: string
   * }
   */
  evaluate(input: object): object
  policyHash(): string
  static compilerVersion(): string
}
